name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: install gems
        run: make install

      - name: lint
        run: bundle exec rubocop

      - name: test
        run: make test
    
